name: Smart Contract CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: contracts

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run tests
        run: npx hardhat test